### ISSUE TITLE
SVG SMIL animations for certain smilies broken in Firefox

### ISSUE THREAD

**Issue by keithpickering** [TheMinusWorld/minus-world-mybb#9]
They're broken in IE too for the record, but I think it was decided early on we're abandoning IE optimization.

I made all the animated smileys using the same method, animating them in Animate CC before exporting them using the Flash2SVG plugin.

I'd love for someone to weigh in on this issue because it's had me stumped for awhile. For the "Yes" and "No" smillies at least, animation is essential.

**Comment by wtl420** [comment]
The animated ones seem to work now, no idea if the browser changed or we fixed them or what.
